### ISSUE TITLE
tests fail w/ mex problems on repo as shipped

### ISSUE THREAD

**Issue by ahbarnett** [AndrewGibbs/PathFinder#2]
Dear Andrew,
I do not have MATLAB Coder. I'm on standard ubuntu 22.04 linux with R2022a. So, I'm trying to get your repo to run.
The only file from testSweet that doens't break for me is LinearTest.
All others give
```
`Unrecognized function or variable 'get_smallest_supset_ball_mex'`
```
So, clearly there is a MEX file missing. Usually you wouldn't ship those in a repo, but would give instructions as to how to compile.
(The compile_all.m fails because it assumes Coder exists. But you don't need Coder to compile MEX files...)

Plus the README.md is missing instructions on how to run a basic test to make sure your installation/download worked.

I am intrigued to see the plots of the contours for the test suite - hoping you can fix the above.
(There is only a 2-page WAVES abstract in print, so far, correct?)
Best, Alex

**Comment by AndrewGibbs** [comment]
Dear Alex,

Thanks for raising this issue, and for your helpful message. I'm sorry you were unable to get it to work, we've been making a lot of changes lately (including removing those old example codes) and finally submitted the paper _today_, hopefully the preprint will be on arxiv tomorrow. There are several examples in there.

I have added a copy+paste-able example to the readme file, which can be used to test the code, thank you for this suggestion.

Regarding MEX compilation, I would love to get your thoughts on the best way to proceed with this. The MEX files were generated using 'Matlab coder' toolbox, which as an intermediate step, generates .c and .h files. I am certain that these intermediate files are sufficient to compile MEX files _without_ 'Matlab coder', but have been unable to find guidance on how to do this. Instead we have produced the MEX files for windows/mac/linux 64bit, and these are included. But it is useful to hear that this is an unusual thing to do.

The issue you were having surprised me, because the linux MEX files should have been included in the repo, but for some unknown reason only 3/5 of them were. I have fixed this now, downloaded it to my linux machine and tested it, using the example in the readme.

I hope that your intrigue has not dwindled since raising this issue, and that you are able to get this working soon.

Best wishes,

Andrew

**Comment by AndrewGibbs** [comment]
Update to the above - the [preprint is now on arxiv](https://arxiv.org/abs/2307.07261), and I have added a reference/link to the readme.

**Comment by AndrewGibbs** [comment]
Hi Alex,

The latest version of PathFinder addresses the issues you describe. Thanks again for raising them. Now:
- I have written the C code myself, rather than using Matlab coder. A single script compiles all the C code into MEX functions.
- This is now tested via GitHub CI - these tests are passing so it should work for you too!
- The README contains installation instructions, and basic examples and tests to check this has worked.
- There are also updated examples in the 'examples' folder, some of which plot contour deformations.

Best wishes,
Andrew
