### ISSUE TITLE
Installation issue: example crashes MATLAB

### ISSUE THREAD

**Issue by fruzsinaagocs** [AndrewGibbs/PathFinder#20]
Setup:
- macOS 14.5 Sonoma
- MATLAB R2024a Update 3 (24.1.0.2603908)
- Xcode 16

To reproduce the problem:
1. Clone the `PathFinder` repository
2. Open MATLAB, navigate to `PathFinder`'s directory, and run `addPaths.m`
3. run `compileAll.m` 
4. run `PathFinder(-1, 1, @(x) sin(x), [1 0 0], 100, 10, 'plot')`

What I experience: 
- Step 3 completes successfully with `Building with 'Xcode with Clang'.
MEX completed successfully.`
- Then Step 4 fails and crashes MATLAB.
I'm happy to include my crash log if that helps. Can you please try reproducing the issue?

**Comment by AndrewGibbs** [comment]
Hi @fruzsinaagocs - I am just changing roles, and will have a Mac in my new job. It may take a few weeks to arrive though. Until then, you can run PathFinder without MEX - instructions are in the README. Sorry for the delay with this.

**Comment by AndrewGibbs** [comment]
Hi again @fruzsinaagocs. I believe I have fixed the Mac issue. Annoyingly, I still cannot incorporate MacOS into the continuous integration unit testing process, I assume due to the GitHub VMs not having the right architecture. But the tests pass on my Mac, for Matlab and Octave. Please can you try compiling again with the latest version?

**Comment by fruzsinaagocs** [comment]
I tried it and the test passes now, thank you!
